name: GCP Terraform

on:
  workflow_dispatch:
  push:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    # GCP Token
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_ACCESS_TOKEN }} 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        # Terraform Cloud
        with:
          terraform_version: 1.1.7
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Plan
        id: plan
        run: terraform plan
        
      - name: Terraform Apply
        id: apply
        run: |
          terraform init
          terraform apply -auto-approve
        
